apiVersion: v1
kind: ConfigMap
metadata:
  name: duckdns
  namespace: duckdns
  labels:
    app: duckdns
    tier: dns
data:
  LOG_FILE: "true"
  PGID: "1000"
  PUID: "1000"
  SUBDOMAINS: mmontes-dev,gosmo-devs
  TZ: Europe/Madrid
