apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdns
  namespace: duckdns
  labels:
    app: duckdns
    tier: dns
spec:
  selector:
    matchLabels:
      app: duckdns
      tier: dns
  template:
    metadata:
      labels:
        app: duckdns
        tier: dns
    spec:
      containers:
        - name: duckdns
          image: linuxserver/duckdns
          imagePullPolicy: Always
          resources:
            requests:
              memory: 64Mi
              cpu: 125m
            limits:
              memory: 128Mi
              cpu: 250m
          envFrom:
            - configMapRef:
                name: duckdns
            - secretRef:
                name: duckdns
